# Generated by Django 5.0 on 2024-02-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.URLField(default='https://www.clipartmax.com/png/middle/141-1418392_overnight-services-bed-icon-png-blue.png'),
        ),
        migrations.AlterField(
            model_name='room',
            name='cover_image',
            field=models.URLField(default='https://www.clipartmax.com/png/middle/141-1418392_overnight-services-bed-icon-png-blue.png'),
        ),
    ]
